create table if not exists public.platform_usage_event (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.business(id) on delete cascade,
  staff_id uuid not null references public."STAFF"(id) on delete cascade,
  event_type text not null check (event_type in ('page_view','activity_ping')),
  page_key text not null check (char_length(page_key) between 1 and 80),
  occurred_at timestamptz not null default now()
);

create index if not exists platform_usage_event_recent_idx on public.platform_usage_event(occurred_at desc);
create index if not exists platform_usage_event_business_recent_idx on public.platform_usage_event(business_id, occurred_at desc);
create index if not exists platform_usage_event_staff_recent_idx on public.platform_usage_event(staff_id, occurred_at desc);
alter table public.platform_usage_event enable row level security;
revoke all on public.platform_usage_event from anon, authenticated;

create or replace function public.record_platform_activity(p_event_type text, p_page_key text)
returns void language plpgsql security definer set search_path = public as $$
declare v_staff public."STAFF"%rowtype;
begin
  if p_event_type not in ('page_view','activity_ping') or p_page_key is null or char_length(p_page_key) not between 1 and 80 then raise exception 'Invalid activity event'; end if;
  select * into v_staff from public."STAFF" where auth_user_id = auth.uid() and is_active = true limit 1;
  if v_staff.id is null then raise exception 'Active staff profile required'; end if;
  if exists(select 1 from public.platform_usage_event where staff_id=v_staff.id and event_type=p_event_type and page_key=p_page_key and occurred_at > now()-interval '2 minutes') then return; end if;
  insert into public.platform_usage_event(business_id,staff_id,event_type,page_key) values(v_staff.business_id,v_staff.id,p_event_type,p_page_key);
end; $$;

create or replace function public.get_platform_usage_activity(p_limit integer default 250)
returns table(id bigint,business_id uuid,business_name text,staff_id uuid,staff_name text,staff_email text,event_type text,page_key text,occurred_at timestamptz)
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_platform_admin() then raise exception 'Platform admin access required'; end if;
  return query select e.id,e.business_id,b.business_name,e.staff_id,concat_ws(' ',s.first_name,s.last_name),s.email,e.event_type,e.page_key,e.occurred_at
  from public.platform_usage_event e join public.business b on b.id=e.business_id join public."STAFF" s on s.id=e.staff_id
  order by e.occurred_at desc limit greatest(1,least(coalesce(p_limit,250),1000));
end; $$;

grant execute on function public.record_platform_activity(text,text) to authenticated;
grant execute on function public.get_platform_usage_activity(integer) to authenticated;
