import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import "./BusinessModules.css";
type Props={businessId:string;readOnly?:boolean;onChanged?:(enabled:ModuleKey[])=>void};
type ModuleKey="grooming"|"pet_sitting"|"boarding_daycare"|"veterinary";
type ModuleRow={module_key:ModuleKey;is_enabled:boolean};
type Entitlement={module_key:ModuleKey;status:string;source:string;expires_at:string|null};
type AccessRequest={id:string;module_key:ModuleKey;request_type:string;status:string;created_at:string};
const definitions:Array<{key:ModuleKey;name:string;description:string;icon:string;access:string}>=[
 {key:"grooming",name:"Grooming",description:"Appointments, grooming notes, photos, report cards, and staff earnings.",icon:"✂️",access:"Included"},
 {key:"pet_sitting",name:"Pet sitting",description:"Home visits, access instructions, care checklists, medications, and visit updates.",icon:"🏠",access:"Paid add-on"},
 {key:"boarding_daycare",name:"Boarding & daycare",description:"Reservations, occupancy, kennels, services, billing, and daily care logs.",icon:"🛏️",access:"Paid add-on"},
 {key:"veterinary",name:"Veterinary",description:"Clinical encounters, medical notes, prescriptions, attachments, and protected access.",icon:"🩺",access:"Approval required"},
];
export default function BusinessModules({businessId,readOnly=false,onChanged}:Props){
 const[rows,setRows]=useState<ModuleRow[]>([]),[entitlements,setEntitlements]=useState<Entitlement[]>([]),[requests,setRequests]=useState<AccessRequest[]>([]),[message,setMessage]=useState(""),[saving,setSaving]=useState<ModuleKey|null>(null);
 async function load(){const[moduleResult,entitlementResult,requestResult]=await Promise.all([supabase.from("business_module").select("module_key, is_enabled").eq("business_id",businessId),supabase.from("business_module_entitlement").select("module_key, status, source, expires_at").eq("business_id",businessId),supabase.from("module_access_request").select("id, module_key, request_type, status, created_at").eq("business_id",businessId).eq("status","pending")]);const error=moduleResult.error||entitlementResult.error||requestResult.error;if(error){setMessage(error.message);return}const loaded=(moduleResult.data as ModuleRow[])??[],owned=(entitlementResult.data as Entitlement[])??[];setRows(loaded);setEntitlements(owned);setRequests((requestResult.data as AccessRequest[])??[]);onChanged?.(loaded.filter(row=>row.is_enabled&&owned.some(item=>item.module_key===row.module_key&&["active","trialing"].includes(item.status))).map(row=>row.module_key))}
 useEffect(()=>{void load()},[businessId]);
 function entitled(key:ModuleKey){return entitlements.some(item=>item.module_key===key&&["active","trialing"].includes(item.status)&&(!item.expires_at||new Date(item.expires_at)>new Date()))}
 async function toggle(key:ModuleKey){if(!entitled(key)){setMessage("This module must be unlocked before it can be enabled.");return}const current=rows.find(row=>row.module_key===key)?.is_enabled??false;if(current&&rows.filter(row=>row.is_enabled&&entitled(row.module_key)).length===1){setMessage("Keep at least one service module enabled.");return}setSaving(key);setMessage("");const result=await supabase.from("business_module").update({is_enabled:!current,enabled_at:!current?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("business_id",businessId).eq("module_key",key);setSaving(null);if(result.error)setMessage(result.error.message);else{setMessage(`${definitions.find(item=>item.key===key)?.name} ${current?"disabled":"enabled"}.`);await load()}}
 async function requestAccess(key:ModuleKey){if(requests.some(item=>item.module_key===key))return;setSaving(key);setMessage("");const requestType=key==="veterinary"?"approval":"upgrade";const result=await supabase.from("module_access_request").insert({business_id:businessId,module_key:key,request_type:requestType,message:key==="veterinary"?"Requesting veterinary module review.":"Requesting a paid module upgrade."});setSaving(null);if(result.error)setMessage(result.error.message);else{setMessage("Request sent to Pawffice HQ. We’ll review it and contact you before access changes.");await load()}}
 return <section className="dashboard-panel settings-section"><div><p className="eyebrow">Service modules</p><h3>Choose what your business offers</h3><p className="settings-help">Entitlements control which modules your subscription owns. Toggles only show or hide modules already available to your business.</p></div>{message&&<p className="module-message" role="status">{message}</p>}<div className="module-grid">{definitions.map(module=>{const hasAccess=entitled(module.key),enabled=hasAccess&&(rows.find(row=>row.module_key===module.key)?.is_enabled??false),pending=requests.some(item=>item.module_key===module.key);return <article className={`module-card ${enabled?"enabled":""} ${!hasAccess?"locked":""}`} key={module.key}><span className="module-icon" aria-hidden="true">{module.icon}</span><div><div className="module-title-line"><h4>{module.name}</h4><span className={`module-access-badge ${hasAccess?"owned":"locked"}`}>{hasAccess?"Unlocked":module.access}</span></div><p>{module.description}</p></div>{hasAccess?<label className="module-toggle"><input type="checkbox" disabled={readOnly||saving!==null} checked={enabled} onChange={()=>void toggle(module.key)}/><span>{saving===module.key?"Saving…":enabled?"Enabled":"Available · hidden"}</span></label>:<div className="module-locked-action"><div><strong>🔒 Module locked</strong><span>{pending?"Your request is awaiting review.":module.key==="veterinary"?"Clinical access must be approved by Pawffice HQ.":"Add this module to your Pawffice HQ subscription."}</span></div>{!readOnly&&<button type="button" disabled={pending||saving!==null} onClick={()=>void requestAccess(module.key)}>{pending?"Request pending":saving===module.key?"Sending…":module.key==="veterinary"?"Request approval":"Request paid upgrade"}</button>}</div>}</article>})}</div></section>;
}
