import{useEffect,useState,type FormEvent}from"react";import{supabase}from"../lib/supabase";import"./PetSitting.css";import"./PetSittingEnhancements.css";
type Props={businessId:string;readOnly?:boolean};type Client={id:number;FirstName:string;LastName:string};type Pet={id:number;PetName:string};type ClientPet={client_id:number;pet_id:number};type Staff={id:string;first_name:string;last_name:string};
type Booking={id:string;client_id:number;start_date:string;end_date:string;status:string;emergency_contact_name:string|null;emergency_contact_phone:string|null;notes:string|null};type BookingPet={booking_id:string;pet_id:number};type Plan={booking_id:string;pet_id:number;feeding:string|null;water:string|null;medication:string|null;potty:string|null;activity:string|null;additional_instructions:string|null};type Visit={id:string;booking_id:string;staff_id:string|null;scheduled_start:string;scheduled_end:string|null;status:string;arrived_at:string|null;departed_at:string|null;checklist:Record<string,boolean>;internal_notes:string|null;parent_update:string|null;photo_path:string|null};type Access={booking_id:string;entry_method:string|null;entry_instructions:string|null;alarm_instructions:string|null;key_return_instructions:string|null};
const blank={client_id:"",start_date:"",end_date:"",emergency_contact_name:"",emergency_contact_phone:"",notes:"",entry_method:"",entry_instructions:"",alarm_instructions:"",key_return_instructions:"",feeding:"",water:"",medication:"",potty:"",activity:"",additional_instructions:""};
export default function PetSitting({businessId,readOnly=false}:Props){const[clients,setClients]=useState<Client[]>([]),[pets,setPets]=useState<Pet[]>([]),[clientPets,setClientPets]=useState<ClientPet[]>([]),[staff,setStaff]=useState<Staff[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[bookingPets,setBookingPets]=useState<BookingPet[]>([]),[plans,setPlans]=useState<Plan[]>([]),[visits,setVisits]=useState<Visit[]>([]),[access,setAccess]=useState<Access[]>([]);const[form,setForm]=useState(blank),[petIds,setPetIds]=useState<number[]>([]),[visitTimes,setVisitTimes]=useState<string[]>([""]),[showForm,setShowForm]=useState(false),[selected,setSelected]=useState<string|null>(null),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[photoVisit,setPhotoVisit]=useState<string|null>(null),[photo,setPhoto]=useState<File|null>(null),[newVisitBooking,setNewVisitBooking]=useState<string|null>(null),[newVisitTime,setNewVisitTime]=useState(""),[newVisitStaff,setNewVisitStaff]=useState(""),[bookingSearch,setBookingSearch]=useState(""),[bookingFilter,setBookingFilter]=useState("active");
async function load(){const[c,p,cp,s,b,bp,pl,v,a]=await Promise.all([supabase.from("CLIENT").select("id, FirstName, LastName").eq("business_id",businessId).is("archived_at",null).order("LastName"),supabase.from("PET").select("id, PetName").eq("business_id",businessId).is("archived_at",null).order("PetName"),supabase.from("client_pet").select("client_id, pet_id"),supabase.from("STAFF").select("id, first_name, last_name").eq("business_id",businessId).eq("is_active",true),supabase.from("pet_sitting_booking").select("*").eq("business_id",businessId).order("start_date",{ascending:false}),supabase.from("pet_sitting_booking_pet").select("booking_id, pet_id"),supabase.from("pet_sitting_care_plan").select("*"),supabase.from("pet_sitting_visit").select("*").order("scheduled_start"),supabase.from("pet_sitting_access").select("*")]);const e=c.error||p.error||cp.error||s.error||b.error||bp.error||pl.error||v.error;if(e)setMessage(e.message);else{setClients(c.data??[]);setPets(p.data??[]);setClientPets(cp.data??[]);setStaff(s.data??[]);setBookings(b.data??[]);setBookingPets(bp.data??[]);setPlans(pl.data??[]);setVisits(v.data??[]);setAccess(a.data??[]);}}
useEffect(()=>{void load()},[businessId]);const clientName=(id:number)=>{const c=clients.find(x=>x.id===id);return c?`${c.FirstName} ${c.LastName}`:"Unknown client"};const petsFor=(id:string)=>bookingPets.filter(x=>x.booking_id===id).map(x=>pets.find(p=>p.id===x.pet_id)?.PetName).filter(Boolean).join(", ");
async function saveBooking(e:FormEvent){
 e.preventDefault();
 if(!petIds.length){setMessage("Select at least one pet.");return}
 setSaving(true);setMessage("");
 const created=await supabase.from("pet_sitting_booking").insert({business_id:businessId,client_id:Number(form.client_id),start_date:form.start_date,end_date:form.end_date,emergency_contact_name:form.emergency_contact_name||null,emergency_contact_phone:form.emergency_contact_phone||null,notes:form.notes||null}).select("id").single();
 if(created.error){setSaving(false);setMessage(created.error.message);return}
 const id=created.data.id;
 const results=await Promise.all([
  supabase.from("pet_sitting_booking_pet").insert(petIds.map(pet_id=>({booking_id:id,pet_id}))),
  supabase.from("pet_sitting_care_plan").insert(petIds.map(pet_id=>({booking_id:id,pet_id,feeding:form.feeding||null,water:form.water||null,medication:form.medication||null,potty:form.potty||null,activity:form.activity||null,additional_instructions:form.additional_instructions||null}))),
  supabase.from("pet_sitting_access").insert({booking_id:id,entry_method:form.entry_method||null,entry_instructions:form.entry_instructions||null,alarm_instructions:form.alarm_instructions||null,key_return_instructions:form.key_return_instructions||null}),
  supabase.from("pet_sitting_visit").insert(visitTimes.filter(Boolean).map(time=>({booking_id:id,scheduled_start:new Date(time).toISOString()}))),
 ]);
 const error=results.find(x=>x.error)?.error;
 if(error)setMessage(error.message);else{setMessage("Pet-sitting booking created.");setForm(blank);setPetIds([]);setVisitTimes([""]);setShowForm(false);await load()}
 setSaving(false);
}
async function updateVisit(visit:Visit,values:Partial<Visit>){const result=await supabase.from("pet_sitting_visit").update({...values,updated_at:new Date().toISOString()}).eq("id",visit.id);if(result.error)setMessage(result.error.message);else await load()}
async function addVisit(bookingId:string){if(!newVisitTime)return;const start=new Date(newVisitTime),end=new Date(start.getTime()+30*60*1000);const result=await supabase.from("pet_sitting_visit").insert({booking_id:bookingId,staff_id:newVisitStaff||null,scheduled_start:start.toISOString(),scheduled_end:end.toISOString()});if(result.error)setMessage(result.error.message);else{setMessage("Visit added.");setNewVisitBooking(null);setNewVisitTime("");setNewVisitStaff("");await load()}}
async function uploadPhoto(visit:Visit){if(!photo)return;const safe=photo.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${businessId}/${visit.booking_id}/${visit.id}-${crypto.randomUUID()}-${safe}`;const uploaded=await supabase.storage.from("pet-sitting-photos").upload(path,photo,{contentType:photo.type});if(uploaded.error)return setMessage(uploaded.error.message);await updateVisit(visit,{photo_path:path});setPhoto(null);setPhotoVisit(null)}
async function openPhoto(path:string){const r=await supabase.storage.from("pet-sitting-photos").createSignedUrl(path,60);if(r.error)setMessage(r.error.message);else window.open(r.data.signedUrl,"_blank","noopener,noreferrer")}
const today=new Date(),todayKey=today.toISOString().slice(0,10),query=bookingSearch.trim().toLowerCase();
const bookingVisits=(id:string)=>visits.filter(v=>v.booking_id===id),completedVisits=(id:string)=>bookingVisits(id).filter(v=>v.status==="completed").length;
const bookingGroup=(b:Booking)=>{if(b.status==="cancelled"||b.status==="canceled")return "cancelled";if(b.status==="completed"||b.end_date<todayKey)return "completed";if(b.start_date>todayKey)return "upcoming";return "active"};
const visibleBookings=bookings.filter(b=>(bookingFilter==="all"||bookingGroup(b)===bookingFilter)&&(!query||`${petsFor(b.id)} ${clientName(b.client_id)} ${b.status}`.toLowerCase().includes(query)));
const visitsToday=visits.filter(v=>v.scheduled_start.slice(0,10)===todayKey&&v.status!=="cancelled"&&v.status!=="canceled").length;
return <><header className="dashboard-header"><div><p className="eyebrow">Pet sitting</p><h2>Visits & care plans</h2></div>{!readOnly&&<button className="primary-button" onClick={()=>setShowForm(!showForm)}>{showForm?"Cancel":"+ New booking"}</button>}</header>{message&&<p className="pet-success">{message}</p>}{showForm&&!readOnly&&<section className="dashboard-panel sitting-form-panel"><form className="sitting-form" onSubmit={saveBooking}><label>Client<select required value={form.client_id} onChange={e=>{setForm({...form,client_id:e.target.value});setPetIds([])}}><option value="">Select client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.FirstName} {c.LastName}</option>)}</select></label><div><strong>Pets</strong><div className="sitting-pet-checks">{pets.filter(p=>clientPets.some(x=>x.client_id===Number(form.client_id)&&x.pet_id===p.id)).map(p=><label key={p.id}><input type="checkbox" checked={petIds.includes(p.id)} onChange={e=>setPetIds(current=>e.target.checked?[...current,p.id]:current.filter(id=>id!==p.id))}/>{p.PetName}</label>)}</div></div><label>Start date<input required type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></label><label>End date<input required type="date" min={form.start_date} value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></label>{(["emergency_contact_name","emergency_contact_phone","entry_method","entry_instructions","alarm_instructions","key_return_instructions","feeding","water","medication","potty","activity","additional_instructions","notes"] as const).map(k=><label className={["entry_instructions","alarm_instructions","key_return_instructions","additional_instructions","notes"].includes(k)?"full":""} key={k}>{k.replaceAll("_"," ")}<textarea value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<div className="full"><strong>Scheduled visits</strong>{visitTimes.map((time,i)=><div className="visit-time-row" key={i}><input required type="datetime-local" value={time} onChange={e=>setVisitTimes(current=>current.map((x,index)=>index===i?e.target.value:x))}/>{visitTimes.length>1&&<button type="button" className="secondary-button" onClick={()=>setVisitTimes(current=>current.filter((_,index)=>index!==i))}>Remove</button>}</div>)}<button type="button" className="secondary-button" onClick={()=>setVisitTimes(current=>[...current,""])}>+ Add visit</button></div><button className="primary-button full" disabled={saving}>{saving?"Saving…":"Create booking"}</button></form></section>}

<section className="sitting-overview" aria-label="Pet-sitting summary"><article><span>Active stays</span><strong>{bookings.filter(b=>bookingGroup(b)==="active").length}</strong><small>Currently in your care</small></article><article><span>Upcoming stays</span><strong>{bookings.filter(b=>bookingGroup(b)==="upcoming").length}</strong><small>Scheduled to begin</small></article><article><span>Visits today</span><strong>{visitsToday}</strong><small>Across all bookings</small></article><article><span>Completed visits</span><strong>{visits.filter(v=>v.status==="completed").length}</strong><small>All recorded visits</small></article></section>
<section className="sitting-booking-controls"><label><span>Find a booking</span><input type="search" value={bookingSearch} onChange={e=>setBookingSearch(e.target.value)} placeholder="Search by pet or client"/></label><div className="sitting-filter-tabs">{(["active","upcoming","completed","cancelled","all"] as const).map(option=><button type="button" className={bookingFilter===option?"active":""} key={option} onClick={()=>setBookingFilter(option)}>{option}</button>)}</div></section>
<div className="sitting-results-heading"><div><p className="eyebrow">Bookings</p><h3>{bookingFilter==="all"?"All pet-sitting stays":`${bookingFilter[0].toUpperCase()}${bookingFilter.slice(1)} stays`}</h3></div><strong>{visibleBookings.length} {visibleBookings.length===1?"booking":"bookings"}</strong></div>
<section className="sitting-grid">{visibleBookings.length===0?<div className="dashboard-panel sitting-empty"><div className="sitting-empty-icon">🐾</div><h3>No matching bookings</h3><p>Try another pet, client, or booking status.</p>{bookingSearch&&<button className="secondary-button" onClick={()=>setBookingSearch("")}>Clear search</button>}</div>:visibleBookings.map(b=>{const total=bookingVisits(b.id).length,done=completedVisits(b.id),progress=total?Math.round(done/total*100):0;return <article className="sitting-booking" key={b.id}><div className="sitting-booking-topline"><span className={`sitting-status ${b.status}`}>{b.status.replace("_"," ")}</span><span>{bookingGroup(b)}</span></div><div className="sitting-booking-summary"><div className="sitting-pet-avatar">{(petsFor(b.id)||"P").slice(0,1).toUpperCase()}</div><div><h3>{petsFor(b.id)||"Pet-sitting booking"}</h3><p>{clientName(b.client_id)}</p><p className="sitting-date-range">{new Date(b.start_date+"T12:00:00").toLocaleDateString()} – {new Date(b.end_date+"T12:00:00").toLocaleDateString()}</p></div><div className="sitting-progress"><strong>{done}/{total} visits</strong><div className="sitting-progress-track"><span style={{width:`${progress}%`}}/></div><small>{progress}% complete</small></div></div><div className="sitting-card-actions"><button className="primary-button" onClick={()=>setSelected(selected===b.id?null:b.id)}>{selected===b.id?"Close details":"View care plan"}</button>{!readOnly&&<button className="secondary-button" type="button" onClick={()=>{setSelected(b.id);setNewVisitBooking(b.id)}}>+ Add visit</button>}</div>{selected===b.id&&<div className="sitting-details">{access.find(a=>a.booking_id===b.id)&&<section className="sensitive-access"><p className="eyebrow">Private home access</p><p><strong>{access.find(a=>a.booking_id===b.id)?.entry_method||"Entry method not listed"}</strong></p><p>{access.find(a=>a.booking_id===b.id)?.entry_instructions}</p><p>{access.find(a=>a.booking_id===b.id)?.alarm_instructions}</p><p>{access.find(a=>a.booking_id===b.id)?.key_return_instructions}</p></section>}{plans.filter(p=>p.booking_id===b.id).map(plan=><section className="care-plan" key={plan.pet_id}><h4>{pets.find(p=>p.id===plan.pet_id)?.PetName}&apos;s care plan</h4>
{Object.entries(plan).filter(([k,v])=>!["id","booking_id","pet_id","created_at","updated_at"].includes(k)&&v).map(([k,v])=><p key={k}><strong>{k.replaceAll("_"," ")}:</strong> {String(v)}</p>)}</section>)}
<div className="visit-list">{!readOnly&&(newVisitBooking===b.id?<div className="add-visit-form"><label>Visit date and time<input type="datetime-local" value={newVisitTime} onChange={e=>setNewVisitTime(e.target.value)}/></label><label>Assigned sitter<select value={newVisitStaff} onChange={e=>setNewVisitStaff(e.target.value)}><option value="">Unassigned</option>{staff.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name}</option>)}</select></label><button className="primary-button" type="button" disabled={!newVisitTime} onClick={()=>void addVisit(b.id)}>Save visit</button><button className="secondary-button" type="button" onClick={()=>{setNewVisitBooking(null);setNewVisitTime("");setNewVisitStaff("")}}>Cancel</button></div>:<button className="secondary-button add-visit-button" type="button" onClick={()=>setNewVisitBooking(b.id)}>+ Add visit</button>)}{visits.filter(v=>v.booking_id===b.id).map(v=>
<article className="visit-card" key={v.id}><div><span className={`sitting-status ${v.status}`}>{v.status.replace("_"," ")}</span><h4>{new Date(v.scheduled_start).toLocaleString()}</h4>{v.arrived_at&&<p className="visit-timestamp"><strong>Arrived:</strong> {new Date(v.arrived_at).toLocaleString()}</p>}{v.departed_at&&<p className="visit-timestamp"><strong>Departed:</strong> {new Date(v.departed_at).toLocaleString()}</p>}<label>Assigned staff<select disabled={readOnly} value={v.staff_id??""} onChange={e=>void updateVisit(v,{staff_id:e.target.value||null})}><option value="">Unassigned</option>{staff.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name}</option>)}</select></label></div><div className="visit-checklist">{["food","water","potty","medication","activity"].map(item=><label key={item}><input type="checkbox" disabled={readOnly} checked={Boolean(v.checklist?.[item])} onChange={e=>void updateVisit(v,{checklist:{...v.checklist,[item]:e.target.checked}})}/>{item}</label>)}</div><div className="visit-log-fields"><label>Internal visit log<textarea placeholder="What happened during this visit?" disabled={readOnly} defaultValue={v.internal_notes??""} onBlur={e=>void updateVisit(v,{internal_notes:e.target.value||null})}/></label><label>Parent-facing update<textarea placeholder="Update to share with the pet parent" disabled={readOnly} defaultValue={v.parent_update??""} onBlur={e=>void updateVisit(v,{parent_update:e.target.value||null})}/></label></div>
<div className="visit-actions">{!v.arrived_at&&!readOnly&&<button className="secondary-button" onClick={()=>void updateVisit(v,{arrived_at:new Date().toISOString(),status:"in_progress"})}>Arrive</button>}{v.arrived_at&&!v.departed_at&&!readOnly&&<button className="primary-button" onClick={()=>void updateVisit(v,{departed_at:new Date().toISOString(),status:"completed"})}>Complete visit</button>}{v.photo_path?<button className="secondary-button" onClick={()=>void openPhoto(v.photo_path!)}>View photo</button>:!readOnly&&<><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{setPhotoVisit(v.id);setPhoto(e.target.files?.[0]??null)}}/>{photoVisit===v.id&&photo&&<button className="secondary-button" onClick={()=>void uploadPhoto(v)}>Upload photo</button>}</>}</div></article>)}</div></div>}</article>})}</section>
</>}
