import { useEffect, useState, type FormEvent } from "react";
import { supabase } from "../lib/supabase";
import "./RebookAppointment.css";
import { addWeeksToLocalDate } from "../lib/scheduling";

type Props={businessId:string;appointmentId:string;sourceStartAt:string;onCreated?:()=>void};
type DayAppointment={id:string;start_at:string;end_at:string};
const intervals=[2,4,6,8,10,12];

export default function RebookAppointment({businessId,appointmentId,sourceStartAt,onCreated}:Props){
 const [open,setOpen]=useState(false),[mode,setMode]=useState<"once"|"series">("once"),[interval,setInterval]=useState(6),[count,setCount]=useState(6),[date,setDate]=useState(""),[time,setTime]=useState("09:00"),[dayAppointments,setDayAppointments]=useState<DayAppointment[]>([]),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 function recommendedDate(weeks:number){return addWeeksToLocalDate(sourceStartAt,weeks)}
 function show(){const source=new Date(sourceStartAt);setDate(recommendedDate(interval));setTime(`${String(source.getHours()).padStart(2,"0")}:${String(source.getMinutes()).padStart(2,"0")}`);setOpen(true);setMessage("")}
 useEffect(()=>{if(!open||!date)return;async function loadDay(){const start=new Date(`${date}T00:00:00`),end=new Date(`${date}T23:59:59`);const {data}=await supabase.from("appointment").select("id,start_at,end_at").eq("business_id",businessId).gte("start_at",start.toISOString()).lte("start_at",end.toISOString()).not("status","in",'("cancelled","void")').order("start_at");setDayAppointments(data??[])}void loadDay()},[businessId,date,open]);
 async function submit(event:FormEvent){event.preventDefault();setSaving(true);setMessage("");const firstStart=new Date(`${date}T${time}:00`);const {data,error}=await supabase.rpc("rebook_appointment",{p_source_appointment_id:appointmentId,p_first_start_at:firstStart.toISOString(),p_interval_weeks:interval,p_occurrence_count:mode==="series"?count:1});setSaving(false);if(error){setMessage(error.message);return}const created=Number((data as {count?:number}|null)?.count??(mode==="series"?count:1));setMessage(created===1?"Next appointment booked.":`${created} repeat appointments booked.`);onCreated?.()}
 return <><button type="button" className="rebook-button" onClick={show}>Book again</button>{open&&<div className="rebook-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><section className="rebook-modal" role="dialog" aria-modal="true" aria-labelledby="rebook-title"><header><div><p className="eyebrow">Client retention</p><h3 id="rebook-title">Book the next appointment</h3><p>The same client, pets, services, duration, and staff will be carried forward.</p></div><button type="button" aria-label="Close" onClick={()=>setOpen(false)}>×</button></header><form onSubmit={submit}><div className="rebook-mode"><button type="button" className={mode==="once"?"active":""} onClick={()=>setMode("once")}>One appointment</button><button type="button" className={mode==="series"?"active":""} onClick={()=>setMode("series")}>Repeat series</button></div><label>Recommended cadence<select value={interval} onChange={event=>{const value=Number(event.target.value);setInterval(value);setDate(recommendedDate(value))}}>{intervals.map(value=><option key={value} value={value}>Every {value} weeks</option>)}</select></label>{mode==="series"&&<label>Number of appointments<select value={count} onChange={event=>setCount(Number(event.target.value))}>{[2,3,4,6,8,10,12,18,24].map(value=><option key={value} value={value}>{value} appointments</option>)}</select></label>}<div className="rebook-date-time"><label>First appointment date<input required type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={event=>setDate(event.target.value)}/></label><label>Time<input required type="time" value={time} onChange={event=>setTime(event.target.value)}/></label></div><aside className="rebook-day"><strong>Calendar for {date?new Date(`${date}T12:00:00`).toLocaleDateString():"selected date"}</strong>{dayAppointments.length===0?<span>No appointments booked yet.</span>:dayAppointments.map(item=><span key={item.id}>{new Date(item.start_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}–{new Date(item.end_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</span>)}</aside>{mode==="series"&&<p className="rebook-preview">Creates {count} appointments, {interval} weeks apart. Any staff conflict stops the entire series before anything is saved.</p>}{message&&<p className={message.includes("booked")?"settings-success":"error-message"}>{message}</p>}<div className="rebook-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-button" disabled={saving}>{saving?"Checking schedule…":mode==="series"?"Book repeat series":"Book appointment"}</button></div></form></section></div>}</>
}
