import { useEffect, useState, type FormEvent } from "react";
import { supabase } from "../lib/supabase";
import "./ReportCards.css";

type Props={businessId:string;readOnly?:boolean};
type Appointment={id:string;client_id:number;start_at:string;status:string};
type Pet={id:number;PetName:string}; type Client={id:number;FirstName:string;LastName:string};
type Link={appointment_id:string;pet_id:number}; type StaffLink={appointment_id:string;staff_id:string|null};
type Staff={id:string;first_name:string;last_name:string};
type Report={id:string;appointment_id:string;pet_id:number;client_id:number;staff_id:string|null;report_type:string;status:string;visit_summary:string|null;behavior:string|null;food:string|null;water:string|null;potty:string|null;medication:string|null;activity:string|null;staff_notes:string|null;before_photo_path:string|null;after_photo_path:string|null;created_at:string;delivered_at:string|null};
const blank={appointment_id:"",report_type:"grooming",visit_summary:"",behavior:"",food:"",water:"",potty:"",medication:"",activity:"",staff_notes:"",status:"draft"};
const esc=(value:string)=>value.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]!);

export default function ReportCards({businessId,readOnly=false}:Props){
 const [appointments,setAppointments]=useState<Appointment[]>([]),[pets,setPets]=useState<Pet[]>([]),[clients,setClients]=useState<Client[]>([]),[links,setLinks]=useState<Link[]>([]),[staffLinks,setStaffLinks]=useState<StaffLink[]>([]),[staff,setStaff]=useState<Staff[]>([]),[reports,setReports]=useState<Report[]>([]);
 const [form,setForm]=useState(blank),[before,setBefore]=useState<File|null>(null),[after,setAfter]=useState<File|null>(null),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[showForm,setShowForm]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[channel,setChannel]=useState("email"),[confirmConsent,setConfirmConsent]=useState(false);
 async function load(){const [a,p,c,l,sl,s,r]=await Promise.all([
  supabase.from("appointment").select("id, client_id, start_at, status").eq("business_id",businessId).not("status","in",'("cancelled","canceled","void")').order("start_at",{ascending:false}),
  supabase.from("PET").select("id, PetName").eq("business_id",businessId),supabase.from("CLIENT").select("id, FirstName, LastName").eq("business_id",businessId),supabase.from("appointment_pet").select("appointment_id, pet_id"),supabase.from("appointment_service").select("appointment_id, staff_id"),supabase.from("STAFF").select("id, first_name, last_name").eq("business_id",businessId),supabase.from("pet_report_card").select("*").eq("business_id",businessId).order("created_at",{ascending:false})]);
  const e=a.error||p.error||c.error||l.error||sl.error||s.error||r.error;if(e)setMessage(e.message);else{setAppointments(a.data??[]);setPets(p.data??[]);setClients(c.data??[]);setLinks(l.data??[]);setStaffLinks(sl.data??[]);setStaff(s.data??[]);setReports((r.data as Report[])??[]);}}
 useEffect(()=>{void load()},[businessId]);
 const petFor=(id:string)=>pets.find(p=>p.id===links.find(l=>l.appointment_id===id)?.pet_id);
 const clientFor=(id:number)=>clients.find(c=>c.id===id); const staffFor=(id:string|null)=>staff.find(s=>s.id===id);
 function closeForm(){setShowForm(false);setEditingId(null);setForm(blank);setBefore(null);setAfter(null)}
 function edit(report:Report){setEditingId(report.id);setForm({appointment_id:report.appointment_id,report_type:report.report_type,visit_summary:report.visit_summary??"",behavior:report.behavior??"",food:report.food??"",water:report.water??"",potty:report.potty??"",medication:report.medication??"",activity:report.activity??"",staff_notes:report.staff_notes??"",status:report.status});setBefore(null);setAfter(null);setShowForm(true);window.scrollTo({top:0,behavior:"smooth"})}
 async function upload(file:File|null,reportId:string,label:string){if(!file)return null;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${businessId}/${reportId}/${label}-${crypto.randomUUID()}-${safe}`;const result=await supabase.storage.from("report-card-photos").upload(path,file,{contentType:file.type});if(result.error)throw result.error;return path;}
 async function save(event:FormEvent){event.preventDefault();const appointment=appointments.find(a=>a.id===form.appointment_id),pet=petFor(form.appointment_id);if(!appointment||!pet)return;setSaving(true);setMessage("");const existing=reports.find(r=>r.id===editingId),staffId=staffLinks.find(x=>x.appointment_id===appointment.id)?.staff_id??null,id=editingId??crypto.randomUUID();try{const newBefore=await upload(before,id,"before"),newAfter=await upload(after,id,"after");const values={business_id:businessId,appointment_id:appointment.id,pet_id:pet.id,client_id:appointment.client_id,staff_id:staffId,report_type:form.report_type,status:form.status,...Object.fromEntries(Object.entries(form).filter(([k])=>!["appointment_id","report_type","status"].includes(k)).map(([k,v])=>[k,v.trim()||null])),before_photo_path:newBefore??existing?.before_photo_path??null,after_photo_path:newAfter??existing?.after_photo_path??null,completed_at:form.status==="completed"?(existing?.status==="completed"?undefined:new Date().toISOString()):null,updated_at:new Date().toISOString()};const result=editingId?await supabase.from("pet_report_card").update(values).eq("id",editingId).eq("business_id",businessId):await supabase.from("pet_report_card").insert({id,...values});if(result.error)throw result.error;if(newBefore&&existing?.before_photo_path)await supabase.storage.from("report-card-photos").remove([existing.before_photo_path]);if(newAfter&&existing?.after_photo_path)await supabase.storage.from("report-card-photos").remove([existing.after_photo_path]);closeForm();setMessage(editingId?"Report card updated.":"Report card saved.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Report card could not be saved.");}finally{setSaving(false)}}
 function summary(report:Report){const pet=pets.find(p=>p.id===report.pet_id);return [`${pet?.PetName??"Your pet"}'s ${report.report_type.replace("_"," ")} report card`,report.visit_summary&&`Visit summary: ${report.visit_summary}`,report.behavior&&`Behavior: ${report.behavior}`,report.food&&`Food: ${report.food}`,report.water&&`Water: ${report.water}`,report.potty&&`Potty: ${report.potty}`,report.medication&&`Medication: ${report.medication}`,report.activity&&`Activity: ${report.activity}`,report.staff_notes&&`Notes: ${report.staff_notes}`].filter(Boolean).join("\n\n")}
 async function send(report:Report){setMessage("");const result=await supabase.functions.invoke("send-client-notification",{body:{appointmentId:report.appointment_id,channel,message:summary(report),confirmSmsConsent:confirmConsent}});if(result.error||result.data?.error){setMessage(result.data?.error??result.error?.message??"Delivery failed");return}await supabase.from("pet_report_card").update({delivered_at:new Date().toISOString()}).eq("id",report.id).eq("business_id",businessId);setMessage("Report card delivered.");await load();}
 async function openPhoto(path:string){const result=await supabase.storage.from("report-card-photos").createSignedUrl(path,60);if(result.error)return setMessage(result.error.message);window.open(result.data.signedUrl,"_blank","noopener,noreferrer");}
 function print(report:Report){const pet=pets.find(p=>p.id===report.pet_id),client=clientFor(report.client_id),worker=staffFor(report.staff_id);const fields=[["Visit summary",report.visit_summary],["Behavior",report.behavior],["Food",report.food],["Water",report.water],["Potty",report.potty],["Medication",report.medication],["Activity",report.activity],["Staff notes",report.staff_notes]].filter(([,v])=>v);const win=window.open("","_blank","width=800,height=900");if(!win)return setMessage("Allow pop-ups to print report cards.");win.document.write(`<!doctype html><title>${esc(pet?.PetName??"Pet")} report card</title><style>body{font:16px Arial;max-width:720px;margin:40px auto;color:#173a35}header{border-bottom:5px solid #00b4d8;padding-bottom:20px}h1{margin:8px 0}.meta{color:#65766f}.field{padding:16px 0;border-bottom:1px solid #dce4e1}.field h3{margin:0 0 6px;text-transform:capitalize}.field p{margin:0;white-space:pre-wrap}@media print{body{margin:20px}}</style><header><small>PAWFFICE HQ · ${esc(report.report_type.replace("_"," ").toUpperCase())}</small><h1>${esc(pet?.PetName??"Pet")}'s Report Card</h1><div class="meta">For ${esc(client?`${client.FirstName} ${client.LastName}`:"Pet parent")} · ${new Date(report.created_at).toLocaleDateString()}${worker?` · By ${esc(`${worker.first_name} ${worker.last_name}`)}`:""}</div></header>${fields.map(([k,v])=>`<section class="field"><h3>${esc(k!)}</h3><p>${esc(v!)}</p></section>`).join("")}<script>window.onload=()=>window.print()<\/script>`);win.document.close();}
 return <><header className="dashboard-header"><div><p className="eyebrow">Client experience</p><h2>Pet report cards</h2></div>{!readOnly&&<button className="primary-button" onClick={()=>showForm?closeForm():setShowForm(true)}>{showForm?"Cancel":"+ New report card"}</button>}</header>{message&&<p className="pet-success" role="status">{message}</p>}
 {showForm&&!readOnly&&<section className="dashboard-panel report-form-panel"><form className="report-form" onSubmit={save}><label className="full">Appointment<select required disabled={editingId!==null} value={form.appointment_id} onChange={e=>setForm({...form,appointment_id:e.target.value})}><option value="">Select appointment</option>{appointments.filter(a=>petFor(a.id)&&(editingId!==null||!reports.some(r=>r.appointment_id===a.id&&r.pet_id===petFor(a.id)?.id))).map(a=><option key={a.id} value={a.id}>{new Date(a.start_at).toLocaleDateString()} · {petFor(a.id)?.PetName} · {clientFor(a.client_id)?.FirstName} {clientFor(a.client_id)?.LastName}</option>)}</select></label><label>Report type<select value={form.report_type} onChange={e=>setForm({...form,report_type:e.target.value})}>{["grooming","daycare","boarding","pet_sitting"].map(x=><option key={x} value={x}>{x.replace("_"," ")}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="completed">Completed</option></select></label>{(["visit_summary","behavior","food","water","potty","medication","activity","staff_notes"] as const).map(key=><label className={key==="visit_summary"||key==="staff_notes"?"full":""} key={key}>{key.replaceAll("_"," ")}<textarea value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Before photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setBefore(e.target.files?.[0]??null)}/></label><label>After photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setAfter(e.target.files?.[0]??null)}/></label><button className="primary-button full" disabled={saving}>{saving?"Saving…":editingId?"Save changes":"Save report card"}</button></form></section>}
 <section className="report-toolbar"><label>Delivery channel<select value={channel} onChange={e=>setChannel(e.target.value)}><option value="email">Email</option><option value="sms">SMS</option><option value="both">Email + SMS</option></select></label>{channel!=="email"&&<label className="consent-check"><input type="checkbox" checked={confirmConsent} onChange={e=>setConfirmConsent(e.target.checked)}/> Confirm SMS consent if needed</label>}</section>
 <section className="report-grid">{reports.length===0?<div className="dashboard-panel empty-state"><h3>No report cards yet</h3><p>Create one from a scheduled or completed appointment.</p></div>:reports.map(r=><article className="report-card" key={r.id}><span className={`report-status ${r.status}`}>{r.status}</span><p className="eyebrow">{r.report_type.replace("_"," ")}</p><h3>{pets.find(p=>p.id===r.pet_id)?.PetName}</h3><p>{new Date(r.created_at).toLocaleDateString()} · {clientFor(r.client_id)?.FirstName} {clientFor(r.client_id)?.LastName}</p>{r.visit_summary&&<p className="report-summary">{r.visit_summary}</p>}{r.before_photo_path&&<button className="secondary-button" onClick={()=>void openPhoto(r.before_photo_path!)}>View before photo</button>} {r.after_photo_path&&<button className="secondary-button" onClick={()=>void openPhoto(r.after_photo_path!)}>View after photo</button>}<div className="report-actions">{!readOnly&&<button className="secondary-button" onClick={()=>edit(r)}>Edit report</button>}<button className="secondary-button" onClick={()=>print(r)}>Print</button>{!readOnly&&r.status==="completed"&&<button className="primary-button" onClick={()=>void send(r)}>{r.delivered_at?"Send again":"Send to parent"}</button>}</div>{r.delivered_at&&<small>Delivered {new Date(r.delivered_at).toLocaleString()}</small>}</article>)}</section></>;
}
