import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import VeterinaryMedications from "./VeterinaryMedications";
import "./VeterinaryMedicationWorkspace.css";

type Props={businessId:string;readOnly?:boolean};
type Pet={id:number;PetName:string;species:string};
type Client={id:number;FirstName:string;LastName:string};
type Link={client_id:number;pet_id:number;is_primary:boolean};
type Order={id:string;pet_id:number;medication_name:string;strength:string|null;frequency:string;refills:number;start_on:string;end_on:string|null;status:string};
type Encounter={id:string;pet_id:number;created_at:string;status:string;chief_complaint:string|null};

export default function VeterinaryMedicationWorkspace({businessId,readOnly=false}:Props){
 const[pets,setPets]=useState<Pet[]>([]),[clients,setClients]=useState<Client[]>([]),[links,setLinks]=useState<Link[]>([]),[orders,setOrders]=useState<Order[]>([]),[encounters,setEncounters]=useState<Encounter[]>([]),[selectedPetId,setSelectedPetId]=useState<number|null>(null),[search,setSearch]=useState(""),[status,setStatus]=useState("active"),[message,setMessage]=useState(""),[renderedAt]=useState(()=>Date.now());
 async function load(){const[petResult,clientResult,linkResult,orderResult,encounterResult]=await Promise.all([supabase.from("PET").select("id, PetName, species").eq("business_id",businessId).is("archived_at",null).order("PetName"),supabase.from("CLIENT").select("id, FirstName, LastName").eq("business_id",businessId).is("archived_at",null),supabase.from("client_pet").select("client_id, pet_id, is_primary"),supabase.from("vet_medication_order").select("id, pet_id, medication_name, strength, frequency, refills, start_on, end_on, status").eq("business_id",businessId).order("start_on",{ascending:false}),supabase.from("vet_encounter").select("id, pet_id, created_at, status, chief_complaint").eq("business_id",businessId).neq("status","entered_in_error").order("created_at",{ascending:false})]);const error=petResult.error||clientResult.error||linkResult.error||orderResult.error||encounterResult.error;if(error)return setMessage(error.message);const loadedPets=(petResult.data as Pet[])??[],loadedOrders=(orderResult.data as Order[])??[];setPets(loadedPets);setClients((clientResult.data as Client[])??[]);setLinks((linkResult.data as Link[])??[]);setOrders(loadedOrders);setEncounters((encounterResult.data as Encounter[])??[]);setSelectedPetId(current=>current??loadedOrders.find(item=>item.status==="active")?.pet_id??loadedPets[0]?.id??null)}
 useEffect(()=>{
  // eslint-disable-next-line react-hooks/set-state-in-effect
  void load();
  // eslint-disable-next-line react-hooks/exhaustive-deps
 },[businessId]);
 function ownerFor(petId:number){const link=links.find(item=>item.pet_id===petId&&item.is_primary)??links.find(item=>item.pet_id===petId);return clients.find(item=>item.id===link?.client_id)}
 const selectedPet=pets.find(item=>item.id===selectedPetId),today=new Date(renderedAt).toISOString().slice(0,10),endingDate=new Date(renderedAt+14*86400000).toISOString().slice(0,10);
 const matchesStatus=(item:Order)=>status==="all"||(status==="ending"?item.status==="active"&&Boolean(item.end_on&&item.end_on>=today&&item.end_on<=endingDate):status==="refills"?item.status==="active"&&item.refills>0:item.status===status);
 const filtered=orders.filter(item=>matchesStatus(item)&&(!search.trim()||`${item.medication_name} ${pets.find(pet=>pet.id===item.pet_id)?.PetName??""} ${ownerFor(item.pet_id)?.FirstName??""} ${ownerFor(item.pet_id)?.LastName??""}`.toLowerCase().includes(search.toLowerCase()))),endingSoon=orders.filter(item=>item.status==="active"&&item.end_on&&item.end_on>=today&&item.end_on<=endingDate).length;
 return <><header className="dashboard-header"><div><p className="eyebrow">Veterinary module</p><h2>Medication workspace</h2><p>Active medication oversight, patient history, and refill details.</p></div></header>{message&&<p className="error-message">{message}</p>}<section className="vet-med-overview"><button type="button" className="clickable-summary-card" onClick={()=>setStatus("active")}><span>Active medications</span><strong>{orders.filter(item=>item.status==="active").length}</strong><small>Show active →</small></button><button type="button" className="clickable-summary-card" onClick={()=>setStatus("ending")}><span>Ending in 14 days</span><strong>{endingSoon}</strong><small>Show ending soon →</small></button><button type="button" className="clickable-summary-card" onClick={()=>setStatus("refills")}><span>Refills authorized</span><strong>{orders.filter(item=>item.status==="active"&&item.refills>0).length}</strong><small>Show refill records →</small></button></section><section className="dashboard-panel vet-med-dashboard"><div className="panel-heading"><div><p className="eyebrow">Practice-wide</p><h3>Medication register</h3></div><div><input type="search" placeholder="Search medication, patient, or owner" value={search} onChange={event=>setSearch(event.target.value)}/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="active">Active</option><option value="ending">Ending in 14 days</option><option value="refills">Refills authorized</option><option value="completed">Completed</option><option value="discontinued">Discontinued</option><option value="all">All</option></select></div></div><div className="vet-med-register">{filtered.length===0?<p>No matching medication records.</p>:filtered.map(item=>{const pet=pets.find(value=>value.id===item.pet_id),owner=ownerFor(item.pet_id);return <button key={item.id} onClick={()=>setSelectedPetId(item.pet_id)}><div><span className={`vet-med-status ${item.status}`}>{item.status}</span><strong>{item.medication_name} {item.strength}</strong><small>{item.frequency} · {item.refills} refill{item.refills===1?"":"s"}</small></div><div><b>{pet?.PetName??"Patient"}</b><small>{owner?`${owner.FirstName} ${owner.LastName}`:"No owner"}</small></div></button>})}</div></section>{selectedPet&&<VeterinaryMedications businessId={businessId} petId={selectedPet.id} petName={selectedPet.PetName} ownerName={ownerFor(selectedPet.id)?`${ownerFor(selectedPet.id)!.FirstName} ${ownerFor(selectedPet.id)!.LastName}`:"Pet parent"} encounters={encounters.filter(item=>item.pet_id===selectedPet.id)} readOnly={readOnly} onChanged={()=>void load()}/>}</>
}
