import { useEffect, useMemo, useState, type FormEvent } from "react";
import { supabase } from "../lib/supabase";
import "./VeterinaryTreatmentPlan.css";

type Props = { businessId:string; encounterId:string; petId:number; petName:string; clientId:number; clientName:string; readOnly?:boolean; onOpenInvoice?:(invoiceId:string)=>void };
type Plan = { id:string; status:string; invoice_id:string|null; notes:string|null; expires_on:string|null; presented_at:string|null };
type Item = { id:string; category:string; description:string; quantity:number; unit_price:number; decision:"pending"|"accepted"|"declined"; decision_note:string|null; sort_order:number };
const blank = { category:"procedure", description:"", quantity:"1", unit_price:"", decision_note:"" };
const money = new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});

export default function VeterinaryTreatmentPlan({businessId,encounterId,petId,petName,clientId,clientName,readOnly=false,onOpenInvoice}:Props){
 const[plan,setPlan]=useState<Plan|null>(null),[items,setItems]=useState<Item[]>([]),[form,setForm]=useState(blank),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 async function load(){const planResult=await supabase.from("vet_treatment_plan").select("id, status, invoice_id, notes, expires_on, presented_at").eq("encounter_id",encounterId).maybeSingle();if(planResult.error){setMessage(planResult.error.message);return}const loaded=(planResult.data as Plan|null)??null;setPlan(loaded);if(!loaded){setItems([]);return}const itemResult=await supabase.from("vet_treatment_plan_item").select("id, category, description, quantity, unit_price, decision, decision_note, sort_order").eq("plan_id",loaded.id).order("sort_order").order("created_at");if(itemResult.error)setMessage(itemResult.error.message);else setItems((itemResult.data as Item[])??[])}
 useEffect(()=>{
  // Loading the encounter's remote plan is the synchronization purpose of this effect.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  void load();
  // eslint-disable-next-line react-hooks/exhaustive-deps
 },[encounterId]);
 const totals=useMemo(()=>items.reduce((sum,item)=>{const amount=Number(item.quantity)*Number(item.unit_price);sum.estimated+=amount;if(item.decision==="accepted")sum.accepted+=amount;if(item.decision==="declined")sum.declined+=amount;return sum},{estimated:0,accepted:0,declined:0}),[items]);
 async function ensurePlan(){if(plan)return plan;const expires=new Date();expires.setDate(expires.getDate()+14);const result=await supabase.from("vet_treatment_plan").insert({business_id:businessId,pet_id:petId,client_id:clientId,encounter_id:encounterId,expires_on:expires.toISOString().slice(0,10)}).select("id, status, invoice_id, notes, expires_on, presented_at").single();if(result.error)throw result.error;const created=result.data as Plan;setPlan(created);return created}
 async function addItem(event:FormEvent){event.preventDefault();setSaving(true);setMessage("");try{const current=await ensurePlan();const result=await supabase.from("vet_treatment_plan_item").insert({plan_id:current.id,category:form.category,description:form.description.trim(),quantity:Number(form.quantity),unit_price:Number(form.unit_price),decision_note:form.decision_note.trim()||null,sort_order:items.length}).select("id, category, description, quantity, unit_price, decision, decision_note, sort_order").single();if(result.error)throw result.error;setItems(rows=>[...rows,result.data as Item]);setForm(blank);setMessage("Estimate item added.")}catch(error){setMessage(error instanceof Error?error.message:"Could not add estimate item.")}finally{setSaving(false)}}
 async function decide(item:Item,decision:Item["decision"]){if(!plan)return;setSaving(true);setMessage("");const result=await supabase.from("vet_treatment_plan_item").update({decision,updated_at:new Date().toISOString()}).eq("id",item.id).eq("plan_id",plan.id);if(result.error){setMessage(result.error.message);setSaving(false);return}await supabase.rpc("refresh_vet_treatment_plan_status",{p_plan_id:plan.id});await load();setSaving(false)}
 async function removeItem(itemId:string){if(!plan||!window.confirm("Remove this item from the estimate?"))return;const result=await supabase.from("vet_treatment_plan_item").delete().eq("id",itemId).eq("plan_id",plan.id);if(result.error)setMessage(result.error.message);else{await supabase.rpc("refresh_vet_treatment_plan_status",{p_plan_id:plan.id});await load()}}
 async function present(){const current=await ensurePlan();const result=await supabase.from("vet_treatment_plan").update({status:"presented",presented_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",current.id).eq("business_id",businessId);if(result.error)setMessage(result.error.message);else{setMessage("Treatment plan marked as presented to the client.");await load()}}
 async function createInvoice(){if(!plan||totals.accepted<=0)return;setSaving(true);setMessage("");const result=await supabase.rpc("invoice_vet_treatment_plan",{p_plan_id:plan.id});setSaving(false);if(result.error)setMessage(result.error.message);else{const invoiceId=String(result.data);setMessage("Accepted items were converted into an invoice.");await load();onOpenInvoice?.(invoiceId)}}
 function printEstimate(){const win=window.open("","_blank","width=850,height=900");if(!win)return setMessage("Allow pop-ups to print the estimate.");const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]!);win.document.write(`<!doctype html><title>${esc(petName)} treatment plan</title><style>body{font:15px Arial;max-width:760px;margin:35px auto;color:#173f55}header{border-bottom:5px solid #00b4d8}table{width:100%;border-collapse:collapse;margin-top:25px}th,td{padding:10px;border-bottom:1px solid #dce6eb;text-align:left}td:last-child,th:last-child{text-align:right}.accepted{color:#17633f}.declined{color:#9e2e20}.totals{margin-top:20px;text-align:right;font-size:18px}@media print{body{margin:.35in}}</style><header><small>VETERINARY ESTIMATE</small><h1>${esc(petName)} Treatment Plan</h1><p>${esc(clientName)}${plan?.expires_on?` · Valid through ${new Date(plan.expires_on+"T00:00:00").toLocaleDateString()}`:""}</p></header><table><thead><tr><th>Recommendation</th><th>Decision</th><th>Qty</th><th>Price</th></tr></thead><tbody>${items.map(item=>`<tr><td>${esc(item.category.replaceAll("_"," "))}: ${esc(item.description)}</td><td class="${item.decision}">${esc(item.decision)}</td><td>${item.quantity}</td><td>${money.format(item.quantity*item.unit_price)}</td></tr>`).join("")}</tbody></table><div class="totals"><p>Estimated total: <strong>${money.format(totals.estimated)}</strong></p><p>Client-approved total: <strong>${money.format(totals.accepted)}</strong></p></div><script>window.onload=()=>window.print()</script>`);win.document.close()}
 const locked=plan?.status==="invoiced";
 return <section className="vet-treatment-plan"><div className="panel-heading"><div><p className="eyebrow">Estimate & approval</p><h4>Treatment plan</h4><p>Recommend care, record the client&apos;s choices, then invoice only accepted items.</p></div>{plan&&<span className={`vet-plan-status ${plan.status}`}>{plan.status.replaceAll("_"," ")}</span>}</div>{message&&<p className="pet-success" role="status">{message}</p>}
 {!readOnly&&!locked&&<form className="vet-plan-add" onSubmit={addItem}><label>Category<select value={form.category} onChange={event=>setForm({...form,category:event.target.value})}>{["service","diagnostic","procedure","medication","hospitalization","other"].map(value=><option value={value} key={value}>{value}</option>)}</select></label><label className="description">Recommendation<input required value={form.description} onChange={event=>setForm({...form,description:event.target.value})} placeholder="CBC/Chemistry panel, dental cleaning, medication…"/></label><label>Quantity<input required type="number" min="0.01" step="0.01" value={form.quantity} onChange={event=>setForm({...form,quantity:event.target.value})}/></label><label>Unit price<input required type="number" min="0" step="0.01" value={form.unit_price} onChange={event=>setForm({...form,unit_price:event.target.value})}/></label><button className="secondary-button" disabled={saving}>+ Add item</button></form>}
 {items.length===0?<div className="vet-plan-empty"><strong>No recommendations yet</strong><span>Add the proposed care and pricing for this encounter.</span></div>:<div className="vet-plan-items">{items.map(item=><article key={item.id} className={item.decision}><div><span>{item.category}</span><strong>{item.description}</strong><small>{item.quantity} × {money.format(Number(item.unit_price))}</small></div><b>{money.format(Number(item.quantity)*Number(item.unit_price))}</b><div className="vet-plan-decisions">{!readOnly&&!locked&&<><button type="button" className={item.decision==="accepted"?"selected accept":"accept"} disabled={saving} onClick={()=>void decide(item,"accepted")}>Accept</button><button type="button" className={item.decision==="declined"?"selected decline":"decline"} disabled={saving} onClick={()=>void decide(item,"declined")}>Decline</button>{item.decision!=="pending"&&<button type="button" disabled={saving} onClick={()=>void decide(item,"pending")}>Reset</button>}<button type="button" className="remove" onClick={()=>void removeItem(item.id)}>Remove</button></>} {locked&&<span>{item.decision}</span>}</div></article>)}</div>}
 {items.length>0&&<footer><div><span>Full estimate <b>{money.format(totals.estimated)}</b></span><span>Accepted <b>{money.format(totals.accepted)}</b></span><span>Declined <b>{money.format(totals.declined)}</b></span></div><div><button type="button" className="secondary-button" onClick={printEstimate}>Print estimate</button>{!readOnly&&!plan?.presented_at&&!locked&&<button type="button" className="secondary-button" onClick={()=>void present()}>Mark as presented</button>}{!readOnly&&!locked&&<button type="button" className="primary-button" disabled={saving||totals.accepted<=0} onClick={()=>void createInvoice()}>Create invoice from accepted</button>}{plan?.invoice_id&&<button type="button" className="primary-button" onClick={()=>onOpenInvoice?.(plan.invoice_id!)}>Open invoice</button>}</div></footer>}
 </section>
}
